### ISSUE TITLE
Feature #1: User can view the list of seasonal anime

### ISSUE THREAD

**Issue by JimmyTran1206** [JimmyTran1206/ajax-project#1]
## 📐 Functionality

> ##### When user browse to the webpage, the default view of the page is a board of seasonal anime. Each anime has their own picture and their title below their picture.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://github.com/JimmyTran1206/ajax-project/assets/67088234/c70c1bb2-13aa-456c-85e0-7d42cdcc5595)
![image](https://github.com/JimmyTran1206/ajax-project/assets/67088234/066a9c25-1d0f-43c0-83ab-b19ea2ef3a4b)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Create the HTML layout
- [x] Style the layout with CSS
- [x] Make `seasonal` and `popular` links 
- [x] Make the search box
- [x] Pull data of seasonal anime from Jikan API
- [x] Display the first 25 seasonal anime
- [x] Create the next page button
- [x] Display the all the seasonal animes, create as many pages as needed. Each page can display a maximum 25 anime to conform with Jikan data.
