### ISSUE TITLE
Feature #2: User can view the list of top popular 25 anime

### ISSUE THREAD

**Issue by JimmyTran1206** [JimmyTran1206/ajax-project#2]
## 📐 Functionality

> ##### Once the user click on the popular link, a list of 25 top popular anime appears

## 🖼️ Wireframes

![image](https://github.com/JimmyTran1206/ajax-project/assets/67088234/a39283c5-2970-4058-89a3-9bcc821ffc3a)
![image](https://github.com/JimmyTran1206/ajax-project/assets/67088234/4d782e8a-364a-4c54-a2a5-f835d7204d0d)

## ✅ Task List

- [x] Create the `Popular` link
- [x] Make layout for the `popular` page
- [x] Make the layout for the `error` page
- [x] Fetch the data for the content of the `popular` page
- [x] Implement error handling for both `popular` and `seasonal` page
- [ ] Make layout for the search box to prepare for the next issue.
